### ISSUE TITLE
Proper Peer Dependency Support 

### ISSUE THREAD

**Issue by sahinvardar** [apimda/npm-layer-version#5]
Currently, this construct relies on specific versions of `aws-cdk-lib` and `constructs` libraries, as indicated [here](https://github.com/apimda/npm-layer-version/blob/73d92a4647f050923c8cfcd8e7fa4f64cdda7e03/package.json#L22).

We aim for these constructs to be compatible with major versions of these dependencies. For instance, this construct should function seamlessly with any version within the 2.x range of `aws-cdk-lib` and the 10.x range of `constructs`. To achieve this, we propose implementing [Peer Dependencies](https://nodejs.org/en/blog/npm/peer-dependencies).

We suggest adding this section to the `package.json` file:

```json
"peerDependencies": {
  "aws-cdk-lib": "^2.0.0",
  "constructs": "^10.0.0"
}
```

This adjustment will ensure compatibility with a broader range of dependency versions.

**Comment by joemays** [comment]
Makes sense, can you create a PR?
